### ISSUE TITLE
tagged release?

### ISSUE THREAD

**Issue by dimalinux** [MarinX/monerorpc#3]
This looks like a nice library! Have you considered making a tagged release? Before the first release, it might be nice if you renamed the module to `github.com/marinx/monerorpc` (lower case to follow best practices).

**Comment by MarinX** [comment]
Hi @dimalinux .
Thanks for the comment.
Yes, I will tag it - great suggestion.
I will tag when I fix other open issues.

**Comment by MarinX** [comment]
tagged with v1.0.0 (included updates)
I dont want to break things so for now, it will be as it is.
