### ISSUE TITLE
Is the Status field in response structures meaningful?

### ISSUE THREAD

**Issue by dimalinux** [MarinX/monerorpc#8]
I noticed that you kept the "Status" field in the response struct types. Is there any API function where the status can have something other than "OK" when no error value was returned?

I realize that I'm asking a question as an issue, but I'm sure others will have the same question. Thanks!

**Comment by MarinX** [comment]
You are talking about GenerateBlocks method? 
Looking at the [source](https://github.com/monero-project/monero/blob/v0.18.1.0/src/rpc/core_rpc_server_commands_defs.h#L1076-L1107), I can see there is no status or untrusted field but provided example contains this.

Can you maybe confirm that the current monero daemon RPC returns the correct JSON result output? (with or without status/untrusted)

**Comment by dimalinux** [comment]
Not just `GenerateBlocks`.  The status field is in all the response types from the daemon. Take `GetBlockHeaderByHeight` as an example with the Status field:
```
type GetBlockHeaderByHeightResponse struct {
	// A structure containing block header information
	BlockHeader BlockHeader `json:"block_header"`
	// General RPC error code. "OK" means everything looks good.
	Status string `json:"status"`
	// States if the result is obtained using the bootstrap mode, and is therefore not trusted (true), or when the daemon is fully synced (false).
	Untrusted bool `json:"untrusted"`
}
```
My conclusion is that the `Status` field can just be ignored.  If there was a general RPC error, the field is not present in the JSON response, and in your response structure it is the empty string.

Here's an error example where you can see that the `result` field and, consequently, the `Status` field are not present:
```
curl http://127.0.0.1:18081/json_rpc -w "\n" -d '{"jsonrpc":"2.0","id":"0","method":"get_block_header_by_height","params":{"hheight":999999999999999999}}' -H 'Content-Type: application/json'
```
```
{
  "error": {
    "code": -2,
    "message": "Requested block height: 999999999999999999 greater than current top block height: 532"
  },
  "id": "0",
  "jsonrpc": "2.0"
}
```
Note that even though the `result` field is not present in the above output, your code will return a non-nil value for the response structure, but all the values inside it will be empty. Changing it to `nil` might be a better option, as it wasn't present in the returned JSON and you are already returning an error.

Here's the same request in a non-error scenario. Note: I'm querying a daemon in regtest mode, not a production daemon:
```
curl http://127.0.0.1:18081/json_rpc --w "\n" -d '{"jsonrpc":"2.0","id":"0","method":"get_block_header_by_height","params":{"height":9}}' -H 'Content-Type: application/json'
```
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "block_header": {
      "block_size": 85,
      "block_weight": 85,
      "cumulative_difficulty": 10,
      "cumulative_difficulty_top64": 0,
      "depth": 523,
      "difficulty": 1,
      "difficulty_top64": 0,
      "hash": "c6d4b16ff18f66c3dd803c2f7b9c464482814d0b0bd499ee9c6fd084a8474465",
      "height": 9,
      [ ... remaining fields removed to save space ...]
    },
    "credits": 0,
    "status": "OK",
    "top_hash": "",
    "untrusted": false
  }
}
```

**Comment by dimalinux** [comment]
I'll close this issue. If you are working on 2.0, maybe there is a way the code can be organized so that there are fewer levels of indirection when accessing the daemon responses. So, maybe, `GetBlockHeaderByHeightResponse` would be the `BlockHeader` directly without nesting. If the only meaningful field in the outer structure is `untrusted`, there might be some alternative way of handling it. Like, say, making `untrusted` generate an error by default unless the library client sets a setting to allow it. (Just throwing out ideas ... I haven't worked enough with daemon client code to know what would best cover 98% of the use cases.) Thanks!

**Comment by MarinX** [comment]
no worries @dimalinux  :) I didn't work with daemon either so I don't know the best practice for usage.
If we can get more people using this library, they can suggest features. As of now, I removed the status because I can see it's pointless and added more testing to it.

Thank you for your time to go over it and for suggesting a valid proposal.

**Comment by MarinX** [comment]
no worries @dimalinux  :) I didn't work with daemon either so I don't know the best practice for usage.
If we can get more people using this library, they can suggest features. As of now, I removed the status because I can see it's pointless and added more testing to it.

Thank you for your time to go over it and for suggesting a valid proposal.
